version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "6543:5432"
  
  main:
    image: python:3.8
    volumes:
      - .:/app
    working_dir: /app
    command: python3 main.py
